# This is a GitHub Actions workflow for the build and deployment of the "Virtual Pet Simulator" Power Platform solution.
# This workflow is triggered manually and does not have input parameters.
# The workflow runs on a Windows runner and uses the "Sandbox" environment.
#
# The workflow perform the following steps:
# 0. Enable git long paths: It enables long paths in git to avoid the "Filename too long" error.
# 1. Checkout the repository.
# 2. Setup msbuild: Using the microsoft/setup-msbuild@v2 GitHub action to install msbuild on the runner.
# 3. Pack solution: Run msbuild after installing it on the "resources/06-CodeItAndShipIt/backend-development/VirtualPetSimulator" folder to create the solution zip file.
# 4. Store the packed solution zip file as an artifact.
# 5. Install the Power Platform CLI using the "microsoft/powerplatform-actions/actions-install@main" GitHub action.
# 6. Deploy: It deploys the solution zip file to the Dataverse environment using the "microsoft/powerplatform-actions/import-solution@main" GitHub action leveraging the "TENANT_ID", "CLIENT_ID" and "CLIENT_SECRET" GitHub environment secrets and the "DATAVERSE_ENVIRONMENT_URL" environment variable.

name: Build and deploy solution

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest
    environment:
        name: 'Sandbox'

    steps:
      - name: Enable git long paths
        run: git config --global core.longpaths true

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v2

      - name: Pack solution
        run: msbuild /t:build /restore
        working-directory: resources/06-CodeItAndShipIt/backend-development/VirtualPetSimulator

      - name: Store packed solution as artifact
        uses: actions/upload-artifact@v4
        with:
          name: solution
          path: resources/06-CodeItAndShipIt/backend-development/VirtualPetSimulator/bin/Debug/VirtualPetSimulator.zip

      - name: Install Power Platform CLI
        uses: microsoft/powerplatform-actions/actions-install@main

      - name: Deploy
        uses: microsoft/powerplatform-actions/import-solution@main
        with:
          app-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          tenant-id: ${{ secrets.TENANT_ID }}
          environment-url: ${{ vars.DATAVERSE_ENVIRONMENT_URL }}
          solution-file: resources/06-CodeItAndShipIt/backend-development/VirtualPetSimulator/bin/Debug/VirtualPetSimulator.zip
          force-overwrite: true
          publish-changes: true
          skip-dependency-check: false
          stage-and-upgrade: false
          run-asynchronously: true
          use-deployment-settings-file: false
          skip-lower-version: false